// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2DdU3StZ-xE6QBIxBwl73CuwYTpTxrAA',
    appId: '1:522823910434:web:b93eaf6a4d186f9a1b367b',
    messagingSenderId: '522823910434',
    projectId: 'khachsan-9cbe6',
    authDomain: 'khachsan-9cbe6.firebaseapp.com',
    databaseURL: 'https://khachsan-9cbe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khachsan-9cbe6.appspot.com',
    measurementId: 'G-L7L7GT14KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWnKScqeslprEaAd9q2HqczNpjGt0yOE',
    appId: '1:522823910434:android:99eec52afe868c021b367b',
    messagingSenderId: '522823910434',
    projectId: 'khachsan-9cbe6',
    databaseURL: 'https://khachsan-9cbe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khachsan-9cbe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv3NGtrPofpSbBzcFef4oo8grxIZsiBZ0',
    appId: '1:522823910434:ios:83fb81e0f5c8e5101b367b',
    messagingSenderId: '522823910434',
    projectId: 'khachsan-9cbe6',
    databaseURL: 'https://khachsan-9cbe6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'khachsan-9cbe6.appspot.com',
    iosBundleId: 'com.example.hotelAppv1',
  );

}

